### ISSUE TITLE
Google Auth 2.0 investigate

### ISSUE THREAD

**Issue by metrondir** [project-studying-dotnet/Streetcode-Server-June#253]

**Comment by Careless-boop** [comment]
**OAuth 2.0**
OAuth stands for Open Authorization. OAuth is an open standard for access delegation. The OAuth protocol was developed as a solution for granting access to a limited set of resources for a predefined period of time without sharing usernames and passwords.
**Terminology**

**1. The client**
When dealing with OAuth, you’ll often come across the terms “client” or “client_id.” In this context, the client does not refer to an end-user or customer.
The term “client” does not mean “end-user” or “customer” in this case. Instead, the term “client” is used to refer to the application that obtaining access to the protected resources.
It is possible that several different clients want access to the same resource.

**2. Resources**
A client has resources which are protected with the OAuth protocol. Often, with resources, we mean API-endpoints.

**3. The authorisation server**
The authorization server is where the client requests the end-user to authenticate and obtain a token that represents the scope of permissions granted to the client. During this process:

The user provides their username and password on the authorization server.
The user can consent or deny access to specific resources based on the application’s request, though this feature may be disabled in some cases.
Only registered clients can request end-users to authenticate, ensuring secure access management.

**4. The end-user**
OAuth is designed to grant access to resources on behalf of someone or something. The end-user can be a person, but the protocol also supports machine-to-machine communication.
This is why there is not too many emphasis on the term “end-user” in the documentation.

Most common workflow:


![Image](https://github.com/user-attachments/assets/11ea5b96-4735-4ba0-b206-04808642303d)
