### ISSUE TITLE
Ignore sensitive data in the project

### ISSUE THREAD

**Issue by vladtymo** [project-studying-dotnet/Streetcode-Server-June#3]
Task - relocate all sensitive data to User Secret (file secrets.json)

**Comment by Careless-boop** [comment]
1. In Visual Studio, right-click the project in Solution Explorer, and select Manage User Secrets from the context menu. This gesture adds a UserSecretsId element, populated with a GUID, to the project file.
2. 
![Image](https://github.com/project-studying-dotnet/Streetcode-Server-June/assets/122560983/952f6efb-c743-4048-9298-b600ae387c72)

2. Then secret.json will appear here:

![Image](https://github.com/project-studying-dotnet/Streetcode-Server-June/assets/122560983/79fcd394-9e2f-4ff7-90cb-35b5d678a2b4)

3.Put data from discord file to this file. Save changes.

*4. Also you can add UserSecrets with integrated terminal, use this command:
```
dotnet user-secrets init
```
after that secret.json file will appear here:
YOUR_USER_FOLDER\AppData\Roaming\Microsoft\UserSecrets\USERSECRET_GUID
