### ISSUE TITLE
Eliminate SQL Injection from the Streetcode.DAL.Repositories.Realizations.Base

### ISSUE THREAD

**Issue by BohdanLytvynov** [project-studying-dotnet/Streetcode-Server-June#55]
Need to prevent a possibility of SQL Injections

**Comment by Shavronskyy** [comment]
public Task ExecuteSqlRaw(string query, params object[] parameters)
    {
        return _dbContext.Database.ExecuteSqlRawAsync(query, parameters);
    }
вимкнули світло тому надсилаю так) пропоную такі зміни
