### ISSUE TITLE
Admin/Interesting facts block

### ISSUE THREAD

**Issue by vladtymo** [project-studying-dotnet/Streetcode-Server-June#75]
Admin/Interesting facts block

![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/af73cb44-b366-405d-a3b6-e37cfeb5544d)

### Acceptance Criteria

1. Admin can add a new fact via "+" button
1.1. System opens a modal window where an Admin can add an image, title and text. All items are mandatory
1.2. Admin can add no more than 600 symbols to main text field and 68 symbols to title. Counter for "symbols left" is displayed
1.3. Admin can add a description for an attached photo. This is not a mandatory field, limited up to 200 symbols.
2. Admin can edit existing facts via "pencil" icon
3. Admin can delete existing facts via "trash" icon
4. All facts are displayed as small blocks with titles on it
5. Admin can reorder facts 
![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/92371c12-0e06-47bc-a6d4-0c072501584b)

**Comment by IrynaNakoneshniuk** [comment]
That needs to be realized:
1.Create:
1.1 Controller:  Action for create FactDTO
1.2 Mediator:  CreateHandler

2.Edit:
2.1 Controller: Action for update FactDTO
2.2 Mediator:  UpdateHandler

3. Delete:
3.1  Controller: Action for delete FactDTO
3.2 Mediator:  DeleteHandler

Common: Tests: Unit tests/Integration tests?
