### ISSUE TITLE
Admin/Art gallery block

### ISSUE THREAD

**Issue by BohdanLytvynov** [project-studying-dotnet/Streetcode-Server-June#78]
**Admin/Art gallery block**

![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/c4cb2b06-45df-44b3-ad7c-efb28327e4c8)

### Acceptance Criteria

1. Admin can upload images
2. Images are displayed in the same way like it is working on user-facing StreetCode 
3. ~~Admin can reorder images~~ will not be implemented in MVP
4. Admin can add title (up to 150 symbols) and description (up to 400 symbols) to images, non-mandatory fields
5. Admin can delete images
![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/4fa98b5b-4ea1-49cd-8325-f4e4bb0d28ff)

**Comment by BohdanLytvynov** [comment]
- How media is beeing uploadet? 
- How media properly stored? 
- How it can be presented to a front?

**Comment by Careless-boop** [comment]
1. Admin can add title (up to 150 symbols) and description (up to 400 symbols) to images, non-mandatory fields should be included in Create handler?
2. Admin can delete images, is it really images or art deleting?
